version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/javascript"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/javascript/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/javascript_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/javascript_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/javascript_ios"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/javascript_linux"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/javascript_macos"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/javascript_web"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/javascript_windows"
    schedule:
      interval: "daily"