name: javascript
description: Enable your app to evaluate javascript programs in an isolated javascript environment
version: 1.0.0

environment:
  sdk: ^3.6.0
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: javascript_android
      ios:
        default_package: javascript_darwin
      macos:
        default_package: javascript_darwin

dependencies:
  flutter:
    sdk: flutter
  javascript_android: ^1.0.0
  javascript_darwin: ^1.0.0
  javascript_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.0.0
  flutter_lints: ^6.0.0

topics:
  - javascript
  - runtime
  - scripting
  - js
  - interop