name: javascript_platform_interface
description: A common platform interface for the javascript_flutter plugin.
repository: https://github.com/predatorx7/javascript_flutter/tree/main/packages/javascript_platform_interface
issue_tracker: https://github.com/predatorx7/javascript_flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+javascript_platform_interface%22
version: 1.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - javascript
  - runtime
  - scripting
  - js
  - interop
