name: javascript_platform_interface
description: A common platform interface for the javascript_flutter plugin.
repository: https://github.com/predatorx7/javascript_flutter/tree/main/packages/javascript_platform_interface
issue_tracker: https://github.com/predatorx7/javascript_flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+javascript_platform_interface%22
version: 2.0.0

environment:
  sdk: ^3.6.0

dependencies:
  plugin_platform_interface: ^2.1.0
  meta: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.16.0

topics:
  - javascript
  - runtime
  - scripting
  - js
  - interop
