name: javascript_android
description: Android implementation of the javascript plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

flutter:
  plugin:
    implements: javascript
    platforms:
      android:
        package: org.reclaimprotocol.javascript_android
        pluginClass: JavaScriptPlugin
        dartPluginClass: JavaScriptAndroid

dependencies:
  flutter:
    sdk: flutter
  javascript_platform_interface:
    path: ../javascript_platform_interface
  logging: ^1.3.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  flutter_lints: ^6.0.0
  pigeon: ^26.0.0
