name: example
description: An example application for the javascript_platform_interface package.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  javascript_platform_interface:
    path: ../

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
