name: javascript_example
description: A example application for the javascript package.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0
  http: ^1.5.0
  logging: ^1.3.0
  javascript_flutter:
    # When depending on this package from a real application you should use:
    #   javascript_flutter: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
