name: javascript_darwin
description: An iOS & MacOS implementation of the javascript plugin
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=3.27.0"

flutter:
  plugin:
    implements: javascript
    platforms:
      ios:
        pluginClass: JavaScriptPlugin
        dartPluginClass: JavaScriptDarwin
        sharedDarwinSource: true
      macos:
        pluginClass: JavaScriptPlugin
        dartPluginClass: JavaScriptDarwin
        sharedDarwinSource: true

dependencies:
  ffi: ^2.0.0
  flutter:
    sdk: flutter
  javascript_platform_interface:
    path: ../javascript_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  vendor: ^0.9.7
