name: javascript_darwin
description: An iOS & MacOS implementation of the javascript plugin
repository: https://github.com/predatorx7/javascript_flutter/tree/main/packages/javascript_darwin
issue_tracker: https://github.com/predatorx7/javascript_flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+javascript_darwin%22
version: 1.0.0

environment:
  sdk: ^3.6.0

flutter:
  plugin:
    implements: javascript
    platforms:
      ios:
        pluginClass: JavaScriptPlugin
        dartPluginClass: JavaScriptDarwin
        sharedDarwinSource: true
      macos:
        pluginClass: JavaScriptPlugin
        dartPluginClass: JavaScriptDarwin
        sharedDarwinSource: true

dependencies:
  ffi: ^2.0.0
  flutter:
    sdk: flutter
  javascript_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  vendor: ^0.9.7

topics:
  - javascript
  - runtime
  - scripting
  - js
  - interop