name: javascript
description: Enable your app to evaluate javascript programs
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

flutter:
  plugin:
    platforms:
      android:
        default_package: javascript_android
      ios:
        default_package: javascript_darwin
      macos:
        default_package: javascript_darwin

dependencies:
  flutter:
    sdk: flutter
  javascript_android:
    path: ../javascript_android
  javascript_darwin:
    path: ../javascript_darwin
  javascript_platform_interface:
    path: ../javascript_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  flutter_lints: ^6.0.0
