name: javascript_android
description: Android implementation of the javascript plugin
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0

flutter:
  plugin:
    implements: javascript
    platforms:
      android:
        package: com.magnificsoftware.javascript_android
        pluginClass: JavaScriptPlugin
        dartPluginClass: JavaScriptAndroid

dependencies:
  flutter:
    sdk: flutter
  javascript_platform_interface:
    path: ../javascript_platform_interface
  logging: ^1.0.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  flutter_lints: ^6.0.0
  pigeon: ^26.0.0
