name: javascript_android
description: Android implementation of the javascript_flutter plugin
repository: https://github.com/predatorx7/javascript_flutter/tree/main/packages/javascript_android
issue_tracker: https://github.com/predatorx7/javascript_flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+javascript_android%22
version: 2.0.0

environment:
  sdk: ^3.6.0
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: javascript
    platforms:
      android:
        package: com.magnificsoftware.javascript_android
        pluginClass: JavaScriptPlugin
        dartPluginClass: JavaScriptAndroid

dependencies:
  flutter:
    sdk: flutter
  javascript_platform_interface: ^1.0.0
  logging: ^1.0.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  flutter_lints: ^6.0.0
  pigeon: ^26.0.0

topics:
  - javascript
  - runtime
  - scripting
  - js
  - interop
